### ISSUE TITLE
Can we retrieve number of laps?

### ISSUE THREAD

**Issue by activelylazy** [chrono-race/chrono-web#16]
Shows on the official site

**Comment by riteshtendulkar** [comment]
This is in block F along with the race name. 
I propose we change race name event to race-meta-data event which will carry name and total laps ( and any other info about the race in the future).

Where do you think we should display it?

**Comment by activelylazy** [comment]
For now the most important thing is for it to be in the session data structure. I'd agree with changing race name to race meta data.

We could change the page 1 presentation so we get "21/71" in the interval column. That could work well. At the minute I have to check the TV to see the total number of laps.

**Comment by activelylazy** [comment]
Also, lap count in page 1 goes to total laps + 1 at the minute. We should probably cap that to total number of lap (i.e. not display 72/71!)

**Comment by riteshtendulkar** [comment]
Ok cool. Assign this to me when you can and ill work on this.

**Comment by riteshtendulkar** [comment]
PR #27 to close this.
