### ISSUE TITLE
Driver selector ordering

### ISSUE THREAD

**Issue by activelylazy** [chrono-race/chrono-web#4]
Fix driver selector ordering - currently by racing number.

Best would be by previous championship order. Alternatively either by current championship order or race order.

**Comment by riteshtendulkar** [comment]
Block cp has current championship standing. 

I suggest we combine drivers by teams in addition to current championship order. I.e. highest placed driver at the top, his team mate after him, then next highest placed driver, them his team mate etc. 

In terms of architecture, is it ok to order them this way on the server for now and display them as it is on the web? Or would you prefer a more complicated but purer approach of both team name and championship order being emitted from the server and web deciding to order them appropriately.

Also, can you please assign this to me?

**Comment by activelylazy** [comment]
I worry this could be a bit confusing. Partially ordered by championship standing but partially not. Maybe a better compromise would be to order by current race order?

**Comment by activelylazy** [comment]
Thinking about it, we could just hard-code the team order. It only changes once a year. I'm happy having to enter in the constructor's championship order once a year by hand!
